### ISSUE TITLE
pSMAC not working: what I am missing?

### ISSUE THREAD

**Issue by vlavorini** [automl/SMAC3#445]
Hello,

I'm trying to make pSMAC work, but I fail. This an example code:

    np.random.seed(3)
    def opt_sin(cfg):
        sleep(np.random.rand()*3)
        print(cfg['x'])
        return np.sin(cfg['x'])

    x_par = UniformFloatHyperparameter("x", -0.1, 1, default_value=0) #10; // 4 - 10
    cs = ConfigurationSpace()
    cs.add_hyperparameter(x_par)

    # Scenario object
    scenario = Scenario({"run_obj": "quality",   # we optimize quality (alternatively runtime)
                         "runcount-limit": 10,  # maximum function evaluations
                         "cs": cs,               # configuration space
                         "deterministic": "true",#, #remember to set np.random.seed(x)
                         "shared_model": "true",
                         'output_dir' : 'logs/SMAC',
                        'input_psmac_dirs' : 'logs/SMAC/as*',
                         })

    smac = SMAC(scenario=scenario, rng=np.random.RandomState(42),
            tae_runner=opt_sin,  run_id=1)

    incumbent = smac.optimize()

I run the same code in two Jupyter notebooks, changing only the `run_id`. I left intentionally the `rng` state the same, to check the behavior.

And actually the two notebooks make exactly the same essay on the parameter `x_par`, in the same order, without taking care of the results from the other notebook.

More: the directory created under `'logs/SMAC` do not start with `as`, as specified with the `input_psmac_dirs` parameter. Instead, they start with `run_`. Maybe this is another effect of the same issue?

What I am doing wrong?

**Comment by mlindauer** [comment]
We fixed some issues related to the directories in our dev branch.
If you replace the following line
```'input_psmac_dirs' : 'logs/SMAC/as*',```
by
```'input_psmac_dirs' : 'logs/SMAC/',```
it works fine with our dev branch.

Please note that nevertheless the first evaluated x is always the default configuration (x=0) regardless whether you use `shared_model` or not.

**Comment by vlavorini** [comment]
FYI: I installed the development branch, but part of the issue is still there: the first five essays are the same in the two notebooks, and only after I get essays with different value.

**Comment by vlavorini** [comment]
So, following the point 4, it's an expected behavior that the firsts five iterations are the same in the two notebooks, since the function to be optimized is cheap (evaluation time ~ milliseconds). That's good!

About your question: no, if I set different randomstates I get different results, as expected. I was setting all the same to actually check that the two instances where in communication.

Thank you for the clarification!
